// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJwoSbFc_CM9s5DE8viqtp-0QhvgkjW88',
    appId: '1:950673729343:web:97cfb6180d7effa304d58a',
    messagingSenderId: '950673729343',
    projectId: 'hub-rpg-5f3e2',
    authDomain: 'hub-rpg-5f3e2.firebaseapp.com',
    databaseURL: 'https://hub-rpg-5f3e2-default-rtdb.firebaseio.com',
    storageBucket: 'hub-rpg-5f3e2.firebasestorage.app',
    measurementId: 'G-0T3PDY35GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxPk9LsnkEzAmRayUWZ6uaBJ6TbGoDFGE',
    appId: '1:950673729343:android:5aa896c4e6ed03b804d58a',
    messagingSenderId: '950673729343',
    projectId: 'hub-rpg-5f3e2',
    databaseURL: 'https://hub-rpg-5f3e2-default-rtdb.firebaseio.com',
    storageBucket: 'hub-rpg-5f3e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTzOQVQJRczqUff02VGph-r3LW-AMQVf4',
    appId: '1:950673729343:ios:16b583e088af3e4d04d58a',
    messagingSenderId: '950673729343',
    projectId: 'hub-rpg-5f3e2',
    databaseURL: 'https://hub-rpg-5f3e2-default-rtdb.firebaseio.com',
    storageBucket: 'hub-rpg-5f3e2.firebasestorage.app',
    iosClientId: '950673729343-bqshqa7pdg6q1u5uv2v4d19jj8j6scrp.apps.googleusercontent.com',
    iosBundleId: 'com.limboos.limboOs',
  );

}